# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [63]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [64]:
# Create a 1-dimensional NumPy array using np.array()
one_dimensional = np.array([1, 2, 3, 4, 5])

# Create a 2-dimensional NumPy array using np.array()
two_dimensional = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)

# Create a 3-dimensional Numpy array using np.array()
three_dimensional = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [1, 2, 3],
        [7, 8, 9]
    ]
]
)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [65]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_dimensional.shape, one_dimensional.ndim, one_dimensional.dtype, one_dimensional.size, type(one_dimensional)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [66]:
# Attributes of 2-dimensional array
two_dimensional.shape, two_dimensional.ndim, two_dimensional.dtype, two_dimensional.size, type(two_dimensional)

((3, 3), 2, dtype('int64'), 9, numpy.ndarray)

In [67]:
# Attributes of 3-dimensional array
three_dimensional.shape, three_dimensional.ndim, three_dimensional.dtype, three_dimensional.size, type(three_dimensional)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [68]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(two_dimensional)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [69]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2), int)
print(ones)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [70]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes = np.zeros((7, 2, 3), dtype=int)
print(zeroes)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [71]:
# Create an array within a range of 0 and 100 with step 3
np.arange(start=0, stop=100, step=3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [72]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0, 10, (7, 2))

array([[0, 8],
       [5, 6],
       [9, 6],
       [9, 2],
       [1, 8],
       [7, 9],
       [6, 8]])

In [73]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3, 2))

array([[0.62789441, 0.19427395],
       [0.07094092, 0.39678383],
       [0.05076853, 0.88661715]])

In [74]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(0, 10, size=(4, 6))
print(random_array)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

`Answer :` 
* The numbers in the array are Same cause np.random provides **pseudo random number**, we have set a random **seed=42**, which provides same random numbers every time.

In [75]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_ar = np.random.randint(1, 10, (3,7))
print("Array we created: \n", random_ar)
# Find the unique numbers in the array you just created
print("\nUnique Numbers: ", np.unique(random_ar))

Array we created: 
 [[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]
 [4 9 2 9 5 2 4]]

Unique Numbers:  [1 2 3 4 5 7 9]


In [76]:
# Find the 0'th index of the latest array you created
random_ar[0] # First row!

array([9, 1, 3, 7, 4, 9, 3])

In [77]:
# Get the first 2 rows of latest array you created
random_ar[:2] # index 0 and 1 (2 excluded)

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [78]:
# Get the first 2 values of the first 2 rows of the latest array
random_ar[:2, :2] # index rows & cols together.

array([[9, 1],
       [5, 3]])

In [79]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_ar2 = np.random.randint(0, 10, (3, 5))
ones = np.ones((3, 5))
print(f"""
Random Array :
{random_ar2}

Ones Array :
{ones}
""")


Random Array :
[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]]

Ones Array :
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



In [80]:
# Add the two arrays together
np.add(random_ar2, ones) # Element-wise Addition.

# np.concatenate([random_ar2, ones]) # Also, we concatenate.

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [81]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [82]:
# Try add the array of ones and the other most recent array together
# np.add(random_ar2, ones)  ## Throws ValueError | incompatible Shapes.

When you try the last cell, it produces an error. Why do think this is?

`Because of incompatible shapes of both arrays, they must be of same shape to perform arithmetic operations element-wise.`

How would you fix it?

`In this case, we can just Transpose one of the array, it will invert it's dimensions to match with other one.`

In [83]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
# Subtract the new array of ones from the other most recent array
random_ar2 - ones # Now they have similar shapes.

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [85]:
# Multiply the ones array with the latest array
ones * random_ar2 # Of Course can use numpy functions i.e. np.multiply()

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [86]:
# Take the latest array to the power of 2 using '**'
random_ar2 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [87]:
# Do the same thing with np.square()
np.square(random_ar2)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [88]:
# Find the mean of the latest array using np.mean()
np.mean(random_ar2)

3.8666666666666667

In [89]:
# Find the maximum of the latest array using np.max()
np.max(random_ar2)

9

In [90]:
# Find the minimum of the latest array using np.min()
np.min(random_ar2)

0

In [91]:
# Find the standard deviation of the latest array
random_ar2.std() # Also np.std(random_ar2)

2.578543947441829

In [92]:
# Find the variance of the latest array
random_ar2.var()

6.648888888888889

In [93]:
# Reshape the latest array to (3, 5, 1)
random_ar2.reshape((3, 5, 1))

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [94]:
# Transpose the latest array
np.transpose(random_ar2)

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

`It switches the Dimensions of the array. Here it converted all rows to cols and vice versa`
`Resulting a dimension from (3, 5) to (5, 3).`

In [95]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_1 = np.random.randint(0, 10, (3,3))
random_2 = np.random.randint(0, 10, (3,2))

print(f"""
random_1:\n
{random_1}

random_2:\n
{random_2}
""")


random_1:

[[9 1 9]
 [3 7 6]
 [8 7 4]]

random_2:

[[1 4]
 [7 9]
 [8 8]]



In [96]:
# Perform a dot product on the two newest arrays you created
random_1 @ random_2 # "@" for dot product | Also, np.dot().

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [97]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_1 = np.random.randint(0, 10, (4, 3)) # Same name as before
random_2 = np.random.randint(0, 10, (4, 3)) 

print(f"""
random_1:\n
{random_1}

random_2:\n
{random_2}
""")


random_1:

[[0 8 6]
 [8 7 0]
 [7 7 2]
 [0 7 2]]

random_2:

[[2 0 4]
 [9 6 9]
 [8 6 8]
 [7 1 0]]



In [98]:
# Perform a dot product on the two newest arrays you created
# random_1.dot(random_2 )   # Throughs ValueError | incompatible shapes.

It doesn't work. How would you fix it?

Cause both arrays have same shape i.e. `(4, 3)`, for dot product we need shapes like
`(x, a) & (a, y)`. So we can **`transpose`** one of the arrays we have.

In [99]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
random_2 @ random_1.T

array([[ 24,  16,  22,   8],
       [102, 114, 123,  60],
       [ 96, 106, 114,  58],
       [  8,  63,  56,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?  `Yes, i got it!!`

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [100]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

# Again!! 😏
random_1 = np.random.randint(1, 10, (7, 7))
random_2 = np.random.randint(1, 10, (7, 7))

In [101]:
# Compare the two arrays with '>'
random_1 > random_2

array([[ True,  True, False, False, False, False,  True],
       [ True, False, False, False,  True, False,  True],
       [ True,  True,  True,  True,  True, False,  True],
       [False, False,  True,  True,  True,  True,  True],
       [ True, False,  True,  True, False, False,  True],
       [ True, False, False, False,  True,  True, False],
       [ True, False,  True,  True,  True,  True,  True]])

What happens when you compare the arrays with `>`?

`Ans:` **It returns boolean array of same length performing ">" element wise.**

In [102]:
# Compare the two arrays with '>='
random_1 >= random_2

array([[ True,  True,  True, False, False, False,  True],
       [ True,  True, False, False,  True, False,  True],
       [ True,  True,  True,  True,  True, False,  True],
       [False, False,  True,  True,  True,  True,  True],
       [ True, False,  True,  True, False, False,  True],
       [ True, False, False, False,  True,  True, False],
       [ True, False,  True,  True,  True,  True,  True]])

In [103]:
# Find which elements of the first array are greater than 7
random_1 > 7
# random_1[random_1 > 7] # we can do boolean indexing to find elements itself.

array([[False, False,  True, False, False,  True, False],
       [False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False],
       [ True, False, False, False,  True,  True, False],
       [ True, False, False, False,  True,  True, False]])

In [104]:
# Which parts of each array are equal? (try using '==')
random_1 == random_2

array([[False, False,  True, False, False, False, False],
       [False,  True, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [105]:
# Sort one of the arrays you just created in ascending order
np.sort(random_1)

array([[3, 5, 6, 7, 7, 8, 8],
       [1, 1, 3, 3, 3, 5, 5],
       [1, 3, 4, 7, 7, 7, 9],
       [3, 4, 4, 5, 7, 7, 7],
       [2, 4, 5, 6, 6, 7, 9],
       [1, 1, 4, 7, 9, 9, 9],
       [3, 5, 6, 7, 8, 9, 9]])

In [106]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_1)

array([[4, 3, 6, 0, 1, 2, 5],
       [1, 5, 0, 2, 4, 3, 6],
       [5, 3, 6, 0, 1, 4, 2],
       [6, 0, 4, 1, 2, 3, 5],
       [1, 5, 3, 0, 4, 6, 2],
       [2, 3, 6, 1, 0, 4, 5],
       [1, 6, 3, 2, 4, 0, 5]])

In [107]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_1)

16

In [108]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_1)

8

In [109]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_1, axis=1)


array([2, 3, 2, 2, 2, 0, 0])

In [110]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_1, axis=0)

array([1, 1, 5, 5, 0, 1, 3])

In [111]:
# Create an array of normally distributed random numbers
np.random.randn(10)

array([ 0.88751161,  0.60548313, -0.72029799, -0.26993377, -0.14346223,
        0.61700378,  1.2489407 ,  0.06564916,  1.16920765,  0.87331697])

In [112]:
# Create an array with 10 evenly spaced numbers between 1 and 100
# np.arange(1, 100, 10) # can do this.
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.

### Finally **Completed !!** 
<img src="https://media.giphy.com/media/mQG644PY8O7rG/giphy.gif">

#### It was Simple but Lengthy !! 