## **NumPy - Numerical Python for Number Processing** 

NumPy is a Library for Processing Large amount of numerical data quickly with ease.

* NumPy is **too Fast** as compared to built-in python methods for Number Processing
* It is used **under the hood** in many other Data-Science & Scientific computing packages as a **Base.**
* It uses vectorization (Avoids Loops) to optimize the processing.
* NumPy Provides robust Data Structures and their methods to work with Numerical Data. (ndArrays)
  
**We'll Learn many things :**
1. Most Used NumPy Data Types & Methods.
2. Creating NumPy Arrays (ndArrays).
3. Creating Multi-dimensional Arrays.
4. Viewing and Selecting NumPy Arrays distinctly.
5. Manipulating Data with these Arrays & many more.

* [Official NumPy Documentation](https://numpy.org/doc/stable/user/) ✅

### `Let's Get Started!!` 
![](https://media.giphy.com/media/0zTmMFCAknk3nsoOFQ/giphy.gif)

In [1]:
import numpy as np

## Data Types & Attributes -

* **ndarray :** is the main Data Type of NumPy.
* ndarray is a Linear Data Structure containing sequences of Numbers mainly.

* ndarray refers to **N-Dimensional Arrays**.

In [2]:
# Creating NumPy's ndarray from python list.
ar_1 = np.array([1, 2, 3])
ar_1

array([1, 2, 3])

In [3]:
type(ar_1) # Type of this array.

numpy.ndarray

**Multi-Dimensional Arrays**

In [4]:
# 2D Array
ar_2 = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

# 3D Array
ar_3 = np.array(
    [[
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
     ],
     [
        [2, 4, 6],
        [8, 10, 12],
        [14, 16, 18]
     ]
    ]
)

In [5]:
## View our arrays
## Our 2D Array
ar_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
## Our 3D Array
ar_3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

## **The Anatomy of a NumPy Array.**

<img src="./Images/NumPy_anatomy.png" width=80%>

**Common Attributes Of NumPy ndarray:**

In [7]:
## Getting Shape of our array:
ar_1.shape # just (3,) cause it has only 1 dimension with 3 elements.

(3,)

In [8]:
## 2D NumPy Array:
ar_2.shape # Height | Length

(3, 3)

In [9]:
## 3D Array:
ar_3.shape # Height | Length | Width
# We can make many dimensional arrays like this.

(2, 3, 3)

In [10]:
## Knowing Number of Dimensions of NumPy Array:
ar_1.ndim, ar_2.ndim, ar_3.ndim 
# They can have many dimensions hence called n-dimensional arrays.

(1, 2, 3)

In [11]:
## Size of an Array | Total Num. of elements.
ar_1.size, ar_2.size, ar_3.size

(3, 9, 18)

In [12]:
## They vary in shape but are shame `numpy.ndarray` objects.
type(ar_1), type(ar_2), type(ar_3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
# Check Data Types of NumPy Arrays
ar_1.dtype, ar_2.dtype, ar_3.dtype # Contains Int64

(dtype('int64'), dtype('int64'), dtype('int64'))

In [14]:
# Pandas uses NumPy under the hood!!
# Let's try to create a DataFrame using ndarray object.
import pandas as pd
pd.DataFrame(ar_2) ## It takes max 2 dimensions

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

#### **Other ways to Create NumPy Arrays :**

In [15]:
## Using numpy.ones & numpy.zeroes functions.

# Create array of given size with all ones.
print("ndarray with ones :", ones:=np.ones((3,2)))
print("\nndarray with zeroes :", zeroes:=np.zeros((2,3)))  # The "Walrus Operator" is OP

ndarray with ones : [[1. 1.]
 [1. 1.]
 [1. 1.]]

ndarray with zeroes : [[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# Data Types of this arrays:
(ones.dtype, zeroes.dtype)

(dtype('float64'), dtype('float64'))

**Getting Random ranges in form of ndarray :**

In [17]:
# np.range(start, end, step)
np.arange(2, 30, 3) # Returns ndarray.

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [18]:
# np.random.randint(start, end, size)
(np_randint := np.random.randint(2, 15, (3, 6)))

array([[12,  9,  3,  7,  6,  2],
       [ 6,  8,  2, 12,  8, 12],
       [ 6,  3, 10, 10, 12,  2]])

In [19]:
# Size and Shape created ndarray.
(np_randint.size, np_randint.shape)

(18, (3, 6))

In [20]:
# np.random.random() 
np.random.random((3, 5)) # returns random float between (0, 1] of given size

array([[0.79238272, 0.18725125, 0.01511848, 0.07959217, 0.42790718],
       [0.724108  , 0.0502499 , 0.46317994, 0.55224648, 0.33274327],
       [0.55044292, 0.46822882, 0.00968689, 0.21132749, 0.37571969]])

In [25]:
## Almost same function to give (0, 1] float as ndarray
np.random.rand(3, 5)

array([[0.97357319, 0.81227723, 0.51862371, 0.84360757, 0.92776943],
       [0.53328993, 0.92899386, 0.46457667, 0.76081758, 0.99387932],
       [0.21324038, 0.97914516, 0.58048596, 0.84745469, 0.46104931]])

### **Pseudo Random Numbers.**

* NumPy random numbers aren't actually pure random.
* They are based on a specific seed set by NumPy itself.
* We can set this `seed` manually to get same random numbers every time.

In [30]:
# Setting random seed
np.random.seed(7)
np.random.random() # same random Float every time.


0.07630828937395717

* **Useful if wanna share our code.**