# **NumPy - Numerical Python for Number Processing** 

NumPy is a Library for Processing Large amount of numerical data quickly with ease.

* NumPy is **too Fast** as compared to built-in python methods for Number Processing
* It is used **under the hood** in many other Data-Science & Scientific computing packages as a **Base.**
* It uses vectorization (Avoids Loops) to optimize the processing.
* NumPy Provides robust Data Structures and their methods to work with Numerical Data. (ndArrays)
  
**We'll Learn many things :**
1. Most Used NumPy Data Types & Methods.
2. Creating NumPy Arrays (ndArrays).
3. Creating Multi-dimensional Arrays.
4. Viewing and Selecting NumPy Arrays distinctly.
5. Manipulating Data with these Arrays & many more.

* [Official NumPy Documentation](https://numpy.org/doc/stable/user/) ✅

### `Let's Get Started!!` 
![](https://media.giphy.com/media/0zTmMFCAknk3nsoOFQ/giphy.gif)

In [1]:
import numpy as np

## Data Types & Attributes -

* **ndarray :** is the main Data Type of NumPy.
* ndarray is a Linear Data Structure containing sequences of Numbers mainly.

* ndarray refers to **N-Dimensional Arrays**.

In [2]:
# Creating NumPy's ndarray from python list.
ar_1 = np.array([1, 2, 3])
ar_1

array([1, 2, 3])

In [3]:
type(ar_1) # Type of this array.

numpy.ndarray

**Multi-Dimensional Arrays**

In [4]:
# 2D Array
ar_2 = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

# 3D Array
ar_3 = np.array(
    [[
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
     ],
     [
        [2, 4, 6],
        [8, 10, 12],
        [14, 16, 18]
     ]
    ]
)

In [5]:
## View our arrays
## Our 2D Array
ar_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
## Our 3D Array
ar_3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

## **The Anatomy of a NumPy Array.**

<img src="./Images/NumPy_anatomy.png" width=80%>

## **Common Attributes Of NumPy ndarray:**

In [7]:
## Getting Shape of our array:
ar_1.shape # just (3,) cause it has only 1 dimension with 3 elements.

(3,)

In [8]:
## 2D NumPy Array:
ar_2.shape # Height | Length

(3, 3)

In [9]:
## 3D Array:
ar_3.shape # Height | Length | Width
# We can make many dimensional arrays like this.

(2, 3, 3)

In [10]:
## Knowing Number of Dimensions of NumPy Array:
ar_1.ndim, ar_2.ndim, ar_3.ndim 
# They can have many dimensions hence called n-dimensional arrays.

(1, 2, 3)

In [11]:
## Size of an Array | Total Num. of elements.
ar_1.size, ar_2.size, ar_3.size

(3, 9, 18)

In [12]:
## They vary in shape but are shame `numpy.ndarray` objects.
type(ar_1), type(ar_2), type(ar_3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [13]:
# Check Data Types of NumPy Arrays
ar_1.dtype, ar_2.dtype, ar_3.dtype # Contains Int64

(dtype('int64'), dtype('int64'), dtype('int64'))

In [14]:
# Pandas uses NumPy under the hood!!
# Let's try to create a DataFrame using ndarray object.
import pandas as pd
pd.DataFrame(ar_2) ## It takes max 2 dimensions

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## **Other ways to Create NumPy Arrays :**

In [15]:
## Using numpy.ones & numpy.zeroes functions.

# Create array of given size with all ones.
print("ndarray with ones :", ones:=np.ones((3,2)))
print("\nndarray with zeroes :", zeroes:=np.zeros((2,3)))  # The "Walrus Operator" is OP

ndarray with ones : [[1. 1.]
 [1. 1.]
 [1. 1.]]

ndarray with zeroes : [[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# Data Types of this arrays:
(ones.dtype, zeroes.dtype)

(dtype('float64'), dtype('float64'))

**Getting Random ranges in form of ndarray :**

In [17]:
# np.range(start, end, step)
np.arange(2, 30, 3) # Returns ndarray.

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [18]:
# np.random.randint(start, end, size)
(np_randint := np.random.randint(2, 15, (3, 6)))

array([[ 3,  5,  6, 13,  8, 13],
       [11, 11,  7, 14,  6,  8],
       [ 3,  3,  4,  3,  9,  2]])

In [19]:
# Size and Shape created ndarray.
(np_randint.size, np_randint.shape)

(18, (3, 6))

In [20]:
# np.random.random() 
np.random.random((3, 5)) # returns random float between (0, 1] of given size

array([[0.03353305, 0.35584394, 0.65963592, 0.19372758, 0.45086015],
       [0.68011776, 0.87532316, 0.37831268, 0.12973828, 0.76496768],
       [0.85955048, 0.72612421, 0.43409485, 0.74069624, 0.32905175]])

In [21]:
## Almost same function to give (0, 1] float as ndarray
np.random.rand(3, 5)

array([[0.73706599, 0.18363325, 0.28975178, 0.71536381, 0.40076156],
       [0.22258452, 0.5775362 , 0.98796638, 0.83751598, 0.59559767],
       [0.93198467, 0.39453143, 0.06510835, 0.76858214, 0.06273995]])

## **Pseudo Random Numbers.**

* NumPy random numbers aren't actually pure random.
* They are based on a specific seed set by NumPy itself.
* We can set this `seed` manually to get same random numbers every time.

In [22]:
# Setting random seed
np.random.seed(7)
np.random.random() # same random Float every time.


0.07630828937395717

* **Useful if wanna share our code.**

## **Viewing Arrays & Matrices :**

* Different ways to view and select ndarrays.

In [23]:
## np.unique() function to get all the unique number of an array.
np.unique(ar_3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 14, 16, 18])

In [24]:
# Indexing in 1D ndarrays. 
ar_1[1] # access element at index 1.

2

In [25]:
# In a 2D ndarray.
# acc. to NumPy Array anatomy.
# Giving just one index finds the that index's row in a 2D Array
print("2D array's row 1st :", ar_2[1]) 

## Indexing single element with given rows and cols.
ar_2[1, 2] # element at (1, 2)

2D array's row 1st : [4 5 6]


6

In [26]:
# 3D Arrays[matrices, rows, cols]
print(ar_3[1]) # getting matrice at width = 1
ar_3[0, 1, 2] # 0-th matrice, 1st row & second col.

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


6

### **Slicing with indexing in ndarrays :**


In [27]:
## Slicing the available dimensions based on given n-dimensional array.
print(ar_1[1:3]) # Like Half-Open Interval (start, end]

[2 3]


In [28]:
# 2D array - getting first 2 rows & columns
ar_2[:2, :2]

array([[1, 2],
       [4, 5]])

In [29]:
# Slicing 3D Arrays.
ar_3[:, 0:2, 1:3]

array([[[ 2,  3],
        [ 5,  6]],

       [[ 4,  6],
        [10, 12]]])

* #### Let's create a ***4-Dimensional*** ndarray :

In [30]:
# Create with `numpy.randint` function
F_dim = np.random.randint(5, size=(2, 2, 2, 2))
F_dim

array([[[[1, 3],
         [3, 4]],

        [[1, 0],
         [1, 2]]],


       [[[2, 0],
         [4, 0]],

        [[4, 0],
         [3, 2]]]])

In [31]:
# Indexing in this 4-th Dimensional array.
F_dim[1, 0, 0, 1]

0

In [32]:
# Similarly slicing can occur.
F_dim[:, :, :, 0]

array([[[1, 3],
        [1, 1]],

       [[2, 4],
        [4, 3]]])

## **Manipulating Arrays & Comparing them :**

####   **Arithmetic between two NumPy Arrays.**

* Here smaller array is broadcasted into larger array.

In [33]:
ar_1, ar_2 # array 1 & 2

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [34]:
ar_3 # array 3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

In [35]:
# Arithmetic operations
ar_1 + ar_2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [36]:
ar_2 - ar_1

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [37]:
ar_2 * ar_1

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [38]:
ar_1 - ar_2

array([[ 0,  0,  0],
       [-3, -3, -3],
       [-6, -6, -6]])

In [39]:
ar_2 * ar_3

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[  2,   8,  18],
        [ 32,  50,  72],
        [ 98, 128, 162]]])

In [40]:
ar_1 * ar_3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[ 2,  8, 18],
        [ 8, 20, 36],
        [14, 32, 54]]])

In [41]:
# Division
ar_1 / ar_3

array([[[1.        , 1.        , 1.        ],
        [0.25      , 0.4       , 0.5       ],
        [0.14285714, 0.25      , 0.33333333]],

       [[0.5       , 0.5       , 0.5       ],
        [0.125     , 0.2       , 0.25      ],
        [0.07142857, 0.125     , 0.16666667]]])

In [42]:
# Floor division
ar_3 // ar_1

array([[[ 1,  1,  1],
        [ 4,  2,  2],
        [ 7,  4,  3]],

       [[ 2,  2,  2],
        [ 8,  5,  4],
        [14,  8,  6]]])

In [43]:
# Exponentiation
ar_2 ** ar_1

array([[  1,   4,  27],
       [  4,  25, 216],
       [  7,  64, 729]])

#### **Arrays broadcasting with `scalers` (single values)**

In [44]:
## We can perform any arithmetic operation between NumPy Arrays & singular values.
ar_1*10

array([10, 20, 30])

In [45]:
ar_3* .5

array([[[0.5, 1. , 1.5],
        [2. , 2.5, 3. ],
        [3.5, 4. , 4.5]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]]])

### **NumPy Provides Built-in functions for this arithmetic operations :**
Like :

* For addition = np.add()
* For multiply = np.multiply()
* etc. more

#### **Aggregation :**
* Performing same operation on a group of things (Numbers) like sum etc.

In [46]:
# Sum all the elements of a python list, tuple etc.
sum([1, 5, 7]) # built-in python function

13

In [47]:
# NumPy's built-in function to sum all numbers of NumPy array object.
np.sum(ar_3)

135

We can use both types of functions interchangeably, there are many aggregation functions available.
But It's best to use :
* `Python's built-in with python's core objects (data-types)`.
* `NumPy's functions with NumPy ndarray objects`.

In [48]:
## Let's create a very Large array for comparing speed of operations.
large_array = np.random.randint(1, 100, size=100000)
large_array

array([ 7, 20, 61, ..., 32, 19, 40])

In [49]:
# Let's Test NumPy's Speed comparable to Python's built-in functions.
%timeit sum(large_array)  # Python's "sum()"
%timeit np.sum(large_array) # NumPy's "np.sum()"

40.9 ms ± 5.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
245 µs ± 66.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [50]:
f"NumPy's np.sum() is {(35*1000)/142:.3f} times faster than Python's sum()"

"NumPy's np.sum() is 246.479 times faster than Python's sum()"

#### **Other Aggregation Functions :**

In [51]:
## Mean of an array
np.mean(ar_3)

7.5

In [52]:
# max of an array
np.max(ar_2)

9

In [53]:
# min of an array
np.min(ar_3)

1

In [54]:
# Standard deviation of an array!
# SD is a measure of how spread out our data is.
np.std(ar_3) # SD = sqrt(variance)

4.7871355387816905

In [61]:
# Variance shows the average degree to which each number is different from the mean of the data.
# Higher variance = wider range of numbers
# Lower variance = smaller range of numbers

np.var(ar_3)

22.916666666666668

In [62]:
# Standard deviance must be == sqrt(variance)
np.std(ar_3)==np.sqrt(np.var(ar_3))

True