## **NumPy - Numerical Python for Number Processing** 

NumPy is a Library for Processing Large amount of numerical data quickly with ease.

* NumPy is **too Fast** as compared to built-in python methods for Number Processing
* It is used **under the hood** in many other Data-Science & Scientific computing packages as a **Base.**
* It uses vectorization (Avoids Loops) to optimize the processing.
* NumPy Provides robust Data Structures and their methods to work with Numerical Data. (ndArrays)
  
**We'll Learn many things :**
1. Most Used NumPy Data Types & Methods.
2. Creating NumPy Arrays (ndArrays).
3. Creating Multi-dimensional Arrays.
4. Viewing and Selecting NumPy Arrays distinctly.
5. Manipulating Data with these Arrays & many more.

* [Official NumPy Documentation](https://numpy.org/doc/stable/user/) ✅

### `Let's Get Started!!` 
![](https://media.giphy.com/media/0zTmMFCAknk3nsoOFQ/giphy.gif)

In [1]:
import numpy as np

## Data Types & Attributes -

* **ndarray :** is the main Data Type of NumPy.
* ndarray is a Linear Data Structure containing sequences of Numbers mainly.

* ndarray refers to **N-Dimensional Arrays**.

In [3]:
# Creating NumPy's ndarray from python list.
ar_1 = np.array([1, 2, 3])
ar_1

array([1, 2, 3])

In [4]:
type(ar_1) # Type of this array.

numpy.ndarray

**Multi-Dimensional Arrays**

In [5]:
# 2D Array
ar_2 = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

# 3D Array
ar_3 = np.array(
    [[
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
     ],
     [
        [2, 4, 6],
        [8, 10, 12],
        [14, 16, 18]
     ]
    ]
)

In [12]:
## View our arrays
## Our 2D Array
ar_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
## Our 3D Array
ar_3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]])

## **The Anatomy of a NumPy Array.**

<img src="./Images/NumPy_anatomy.png" width=80%>